name: macOS

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    paths-ignore:
      - '**.md'

env:
  REMOVE_BUNDLED_BOOST : rm -rf /usr/local/share/boost
  CCACHE_SETTINGS: |
        ccache --max-size=150M
        ccache --set-config=compression=true

jobs:
  macos:
    runs-on: macos-latest
    env:
      HOMEBREW_MAKE_JOBS: 2
      HOMEBREW_NO_AUTO_UPDATE: 1
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: /Users/runner/Library/Caches/ccache
        key: ccache-${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ccache-${{ runner.os }}-build-
    - name: install dependencies
      run: |
        brew install hidapi openssl zmq libpgm miniupnpc ldns expat libunwind-headers protobuf ccache
        brew install mitchellh/gon/gon
        brew install --build-from-source ./utils/homebrew/boost@169.rb
    - name: build
      run: |
        ${{env.CCACHE_SETTINGS}}
        make release-static-mac-x86_64 -j${HOMEBREW_MAKE_JOBS}
    - name: Import Code-Signing Certificates for macOS
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.MAC_DEVELOPER_CERT }}
        p12-password: ${{ secrets.MAC_DEVELOPER_PASS }}
    - run: make ci-release
    - run: chmod +x build/packaged/lethean*
    - name: Codesign
      env:
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      run: |
          cp LICENSE build/packaged/LICENSE
          gon -log-level=info ./.github/gon-notarize.json
    - uses: actions/upload-artifact@v2
      with:
        name: macOS
        path: |
           lethean-cli-macos.dmg
           lethean-cli-macos.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          lethean-cli-macos.dmg
          lethean-cli-macos.zip

